/// Flutter icons BarIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BarIcon
///      fonts:
///       - asset: fonts/BarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BarIcon {
  BarIcon._();

  static const _kFontFam = 'BarIcon';
  static const _kFontPkg = null;

  static const IconData handpoint_01 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homenew2_01 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapfigmaver_01 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pennofont_01 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingnopccu_01_01 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
