/// Flutter icons HomeIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcon
///      fonts:
///       - asset: fonts/HomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIcon {
  HomeIcon._();

  static const _kFontFam = 'HomeIcon';
  static const _kFontPkg = null;

  static const IconData pccusetting_01__2_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointplus_01__2_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peoplepointword_01 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
