/// Flutter icons ListIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ListIcon
///      fonts:
///       - asset: fonts/ListIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ListIcon {
  ListIcon._();

  static const _kFontFam = 'ListIcon';
  static const _kFontPkg = null;

  static const IconData listicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
